language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  except:
    - python3
install:
 - pip install typing coverage pytest pytest-cov cryptography idna requests requests-toolbelt trio curio
script:
 - pytest --cov=dns --cov-report=xml:coverage.xml
after_success:
 - bash <(curl -s https://codecov.io/bash)
