language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  #- "nightly"
matrix:
  allow_failures:
    - python: nightly
branches:
  except:
    - python3
install:
 - pip install unittest2 pylint pycrypto ecdsa idna
script:
 - make lint
 - make test
